baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = "Collectif Novart"
  subtitle    = "Ensemble de Musique"
  copyright   = "© 2021"

  cover       = "img/logo2_rect.png"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""


  fbName = "collectifnovart"
  githubName = "kontrabass2018"
  igName = "collectif.novart"
  mediumName = ""

  logo = ""
  orgName = "Collectif Novart"
  orgWebsite = "https://novartensemble.com"
  orgDescription = "Ensemble de Musique Novart S.E.N.C"

  showSupport = true

  author = "Leonardo"
  authorAvatar = "img/logo2_square.png"
  authorLocation = "Montréal, QC, CAN"
  authorWebsite = "https://kontrabass2018.github.io"
  authorDescription = "Coder, Developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"


[[menu.main]]
  name = "Accueil"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Membres"
  url = "/categories/membre/"
  weight = 100


[[menu.main]]
  name = "Concerts"
  url = "/Categories/concert"
  weight = 99

[[menu.main]]
  name = "Projets"
  url = "/categories/projet/"
  weight = 98

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 95


